/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tictactoe;

/**
 *
 * @author Anuradha
 */
public class Extra extends javax.swing.JFrame {

    /**
     * Creates new form Extra
     */
    public Extra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewPlayerPlanel = new javax.swing.JPanel();
        newPlayerQuitGameBtn = new javax.swing.JButton();
        newPlayerNameLabel = new javax.swing.JLabel();
        newPlayerBackBtn = new javax.swing.JButton();
        playerNameText = new javax.swing.JTextField();
        addPlayerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewPlayerPlanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 102, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 153, 0)));

        newPlayerQuitGameBtn.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        newPlayerQuitGameBtn.setText("Quit Game");
        newPlayerQuitGameBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        newPlayerQuitGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlayerQuitGameBtnActionPerformed(evt);
            }
        });

        newPlayerNameLabel.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        newPlayerNameLabel.setText("Player Name");

        newPlayerBackBtn.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        newPlayerBackBtn.setText("Back");
        newPlayerBackBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        newPlayerBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlayerBackBtnActionPerformed(evt);
            }
        });

        playerNameText.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        playerNameText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        addPlayerBtn.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        addPlayerBtn.setText("Add Player");
        addPlayerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        addPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewPlayerPlanelLayout = new javax.swing.GroupLayout(NewPlayerPlanel);
        NewPlayerPlanel.setLayout(NewPlayerPlanelLayout);
        NewPlayerPlanelLayout.setHorizontalGroup(
            NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPlayerPlanelLayout.createSequentialGroup()
                .addGroup(NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPlayerPlanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newPlayerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playerNameText))
                    .addGroup(NewPlayerPlanelLayout.createSequentialGroup()
                        .addGroup(NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewPlayerPlanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(newPlayerBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newPlayerQuitGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewPlayerPlanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(addPlayerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewPlayerPlanelLayout.setVerticalGroup(
            NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPlayerPlanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlayerNameLabel)
                    .addComponent(playerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addPlayerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(NewPlayerPlanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPlayerQuitGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPlayerBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 97, Short.MAX_VALUE)
                    .addComponent(NewPlayerPlanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 97, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(NewPlayerPlanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPlayerQuitGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlayerQuitGameBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit the game?", "Quit Game", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_newPlayerQuitGameBtnActionPerformed

    private void newPlayerBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlayerBackBtnActionPerformed

        NewPlayerPlanel.setVisible(false);
        playBtn.setVisible(false);
        singlePlayerBtn.setVisible(true);
        twoPlayerBtn.setVisible(true);
        quitGameBtn.setVisible(true);
    }//GEN-LAST:event_newPlayerBackBtnActionPerformed

    private void addPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPlayerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewPlayerPlanel;
    private javax.swing.JButton addPlayerBtn;
    private javax.swing.JButton newPlayerBackBtn;
    private javax.swing.JLabel newPlayerNameLabel;
    private javax.swing.JButton newPlayerQuitGameBtn;
    private javax.swing.JTextField playerNameText;
    // End of variables declaration//GEN-END:variables
}
