/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TicTacToeInterface.java
 *
 * Created on Nov 17, 2013, 8:59:52 PM
 */
package tictactoe;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author User
 */
public class TicTacToeDualVersion extends javax.swing.JDialog {

    
    JButton[][] btn_array = new JButton[3][3];

    TicTacToeDualVersionLogic logic;

    

    /** Creates new form TicTacToeInterface */
    public TicTacToeDualVersion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btn_array[0][0] = Btn1;
        btn_array[0][1] = Btn2;
        btn_array[0][2] = Btn3;
        btn_array[1][0] = Btn4;
        btn_array[1][1] = Btn5;
        btn_array[1][2] = Btn6;
        btn_array[2][0] = Btn7;
        btn_array[2][1] = Btn8;
        btn_array[2][2] = Btn9;

        logic = new TicTacToeDualVersionLogic(btn_array);
    }

    

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        wonLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setBackground(java.awt.Color.black);
        setResizable(false);

        titleLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titleLbl.setText("Tic Tac Toe");

        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EMOTICON SMILE.png"))); // NOI18N
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nameLbl.setText("Copyrights : T&A");

        wonLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
            }
        });
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
            }
        });

        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
            }
        });

        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn4MouseClicked(evt);
            }
        });

        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
        });

        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
        });

        Btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn7MouseClicked(evt);
            }
        });

        Btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn8MouseClicked(evt);
            }
        });

        Btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(wonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(wonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked

        logic.initialize();
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                btn_array[i][j].setIcon(null);
                btn_array[i][j].setEnabled(true);
            }
        }
        startBtn.setIcon(new ImageIcon(getClass().getResource("/images/EMOTICON SMILE.png")));
        wonLbl.setText("");
        
    }//GEN-LAST:event_startBtnMouseClicked

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked

        int click = logic.click(0, 0, 0);
        if(click == 1){
            Btn1.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn1.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }


}//GEN-LAST:event_Btn1MouseClicked

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked
        int click = logic.click(1, 0, 1);
        if(click == 1){
            Btn2.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn2.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }

    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked
        int click = logic.click(2, 0, 2);
        if(click == 1){
            Btn3.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn3.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }

}//GEN-LAST:event_Btn3MouseClicked

    private void Btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseClicked
        int click = logic.click(3, 1, 0);
        if(click == 1){
            Btn4.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn4.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
}//GEN-LAST:event_Btn4MouseClicked

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked

        int click = logic.click(4, 1, 1);
        if(click == 1){
            Btn5.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn5.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
        
}//GEN-LAST:event_Btn5MouseClicked

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        int click = logic.click(5, 1, 2);
        if(click == 1){
            Btn6.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn6.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
}//GEN-LAST:event_Btn6MouseClicked

    private void Btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn7MouseClicked
        int click = logic.click(6, 2, 0);
        if(click == 1){
            Btn7.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn7.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
}//GEN-LAST:event_Btn7MouseClicked

    private void Btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn8MouseClicked
        int click = logic.click(7, 2, 1);
        if(click == 1){
            Btn8.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn8.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
}//GEN-LAST:event_Btn8MouseClicked

    private void Btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn9MouseClicked
        int click = logic.click(8, 2, 2);
        if(click == 1){
            Btn9.setIcon(new ImageIcon(getClass().getResource("/images/circle.jpg")));
            if(logic.isPlayerWon(1)){
                wonLbl.setText("Congradulations!  \nPlayer 1 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }else if(click == 2){
            Btn9.setIcon(new ImageIcon(getClass().getResource("/images/cross.jpg")));
            if(logic.isPlayerWon(2)){
                wonLbl.setText("Congradulations!  \nPlayer 2 Won!");
                startBtn.setIcon(new ImageIcon(getClass().getResource("/images/smile.png")));
            }
        }
        
}//GEN-LAST:event_Btn9MouseClicked

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TicTacToeDualVersion dialog = new TicTacToeDualVersion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel wonLbl;
    // End of variables declaration//GEN-END:variables
}
